version: '2'

services:
  app:
    image: microsoft/dotnet
    ports:
      - 5000:80
    volumes:
      - .:/home
    working_dir: /home
    environment:
      - ASPNETCORE_URLS=http://+:80
      - PORT=80
    command: dotnet run
  code:
    image: microsoft/dotnet
    volumes:
      - .:/home
    working_dir: /home
    command: /bin/bash